# Generated by Django 3.1.7 on 2021-02-27 18:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='media/project/%Y/%m/%d')),
            ],
        ),
    ]
