# Generated by Django 3.1.6 on 2021-02-19 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210219_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtuber',
            name='created_data',
        ),
        migrations.AddField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
