# Generated by Django 3.1.7 on 2021-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('insta', models.CharField(max_length=255)),
                ('fb', models.CharField(max_length=255)),
                ('tweeter', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
            ],
        ),
    ]
